from pydantic import BaseModel
import pandas as pd

class InputData(BaseModel):
    id: int | None
    dt: str | None
    turn_cur_cr_avg_act_v2: float | None
    salary_6to12m_avg: float | None
    hdb_bki_total_max_limit: str | None
    dp_ils_paymentssum_avg_12m: float | None
    hdb_bki_total_cc_max_limit: str | None
    incomeValue: float | None
    gender: str | None
    avg_cur_cr_turn: float | None
    adminarea: str | None
    turn_cur_cr_avg_v2: float | None
    turn_cur_cr_max_v2: float | None
    hdb_bki_total_pil_max_limit: str | None
    age: float | None
    dp_ils_avg_salary_1y: float | None
    turn_cur_cr_sum_v2: float | None
    by_category__amount__sum__eoperation_type_name__ishodjaschij_bystryj_platezh_sbp: float | None
    turn_cur_db_sum_v2: float | None
    turn_cur_db_avg_act_v2: float | None
    dp_ils_avg_salary_2y: float | None
    curr_rur_amt_cm_avg: float | None
    turn_cur_db_avg_v2: float | None
    by_category__amount__sum__eoperation_type_name__vhodjaschij_bystryj_platezh_sbp: float | None
    dp_ils_paymentssum_avg_6m: float | None
    avg_cur_db_turn: float | None
    hdb_bki_active_cc_max_limit: str | None
    incomeValueCategory: float | None
    avg_by_category__amount__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: float | None
    avg_credit_turn_rur: float | None
    dp_ils_salary_ratio_1y3y: float | None
    by_category__amount__sum__eoperation_type_name__perevod_po_nomeru_telefona: float | None
    turn_cur_cr_7avg_avg_v2: float | None
    dp_ils_accpayment_avg_12m: float | None
    curbal_usd_amt_cm_avg: float | None
    avg_by_category__amount__sum__cashflowcategory_name__supermarkety: float | None
    avg_loan_cnt_with_insurance: float | None
    avg_by_category__amount__sum__cashflowcategory_name__gipermarkety: float | None
    city_smart_name: str | None
    uniV5: float | None
    turn_cur_db_max_v2: float | None
    avg_by_category__amount__sum__cashflowcategory_name__kafe: float | None
    turn_other_db_max_v2: float | None
    turn_cur_cr_min_v2: float | None
    hdb_bki_other_active_pil_outstanding: str | None
    dp_ewb_last_employment_position: str | None
    turn_cur_db_min_v2: float | None
    hdb_bki_total_products: str | None
    per_capita_income_rur_amt: float | None
    avg_debet_turn_rur: float | None
    hdb_relend_active_max_psk: float | None
    dda_rur_amt_curr_v2: float | None
    mob_cnt_days: float | None
    dp_ils_days_from_last_doc: float | None
    avg_6m_money_transactions: float | None
    transaction_category_supermarket_percent_cnt_2m: float | None
    pil: float | None
    hdb_bki_total_max_overdue_sum: str | None
    avg_6m_clothing: float | None
    avg_by_category__amount__sum__cashflowcategory_name__elektronnye_dengi: float | None
    addrref: str | None
    bki_total_auto_cnt: str | None
    dp_payoutincomedata_payout_avg_3_month: float | None
    hdb_outstand_sum: float | None
    avg_3m_money_transactions: float | None
    dp_address_unique_regions: str | None
    min_balance_rur_amt_6m_af: float | None
    transaction_category_supermarket_sum_cnt_m3_4: float | None
    dp_payoutincomedata_payout_max_3_month: float | None
    hdb_bki_total_ip_max_limit: str | None
    hdb_bki_total_cnt: str | None
    blacklist_flag: float | None
    bki_total_oth_cnt: str | None
    dp_payoutincomedata_payout_sum_3_month: float | None
    hdb_relend_outstand_sum: float | None
    total_rur_amt_cm_avg: float | None
    mob_cover_days: float | None
    dp_payoutincomedata_payout_max_6_month: float | None
    label_Below_50k_share_r1: float | None
    turn_fdep_db_sum_v2: float | None
    dp_ils_accpayment_avg_6m_current: float | None
    transaction_category_cash_percent_amt_2m: float | None
    curr_rur_amt_3m_avg: float | None
    transaction_category_restaurants_sum_amt_m2: float | None
    loan_cnt: float | None
    turn_fdep_db_avg_v2: float | None
    turn_cur_db_7avg_avg_v2: float | None
    bki_total_ip_max_outstand: str | None
    amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__vydacha_nalichnyh_v_bankomate: float | None
    profit_income_out_rur_amt_12m: float | None
    avg_6m_hotels: float | None
    hdb_ovrd_sum: float | None
    dp_ils_total_seniority: float | None
    dp_ils_paymentssum_avg_6m_current: float | None
    smsInWavg6m: float | None
    avg_fdep_db_turn: float | None
    device_iphone_avg: float | None
    by_category__amount__sum__eoperation_type_name__platezh_za_mobilnyj_cherez_ps: float | None
    avg_balance_rur_amt_1m_af: float | None
    curr_rur_amt_cm_avg_period_days_ago_v2: float | None
    avg_by_category__amount__sum__cashflowcategory_name__oteli: float | None
    hdb_bki_total_ip_cnt: str | None
    hdb_bki_active_cc_max_outstand: str | None
    hdb_other_outstand_sum: float | None
    days_to_last_transaction: float | None
    hdb_bki_total_pil_max_overdue: str | None
    vert_pil_last_credit_step_screen_view_3m: float | None
    acard: float | None
    bki_total_il_max_limit: str | None
    other_credits_count: float | None
    tz_msk_timedelta: float | None
    turn_save_db_min_v2: float | None
    profit_income_out_rur_amt_9m: float | None
    dp_ils_ipkcurrentyear_currentyearpensfactor: float | None
    avg_by_category__amount__sum__cashflowcategory_name__odezhda: float | None
    cntOnnRinCallAvg6m: float | None
    dda_rur_amt_3m_avg: float | None
    winback_cnt: float | None
    salary_median_in_gex_r1: float | None
    dp_payoutincomedata_payout_avg_prev_year: float | None
    avg_amount_daily_transactions_90d: float | None
    vert_has_app_ru_tinkoff_investing: float | None
    transaction_category_supermarket_inc_cnt_2m: float | None
    vert_pil_sms_success_3m: float | None
    min_balance_rur_amt_1m_af: float | None
    dp_ils_max_seniority: float | None
    avg_by_category__amount__sum__cashflowcategory_name__set_supermarketov: float | None
    label_500k_to_1M_share_r1: float | None
    avg_by_category__amount__sum__cashflowcategory_name__zarubezhnye_finansovye_operatsii: float | None
    bki_total_products: str | None
    avg_6m_all: float | None
    dp_ils_avg_simultanious_jobs_5y: float | None
    dp_ewb_dismissal_due_contract_violation_by_lb_cnt: float | None
    summarur_1m_purch: float | None
    diff_avg_cr_db_turn: float | None
    dp_ils_cnt_changes_1y: float | None
    dp_ils_employeers_cnt_last_month: float | None
    dp_payoutincomedata_payout_avg_6_month: float | None
    dp_ewb_last_organization: float | None
    by_category__amount__sum__eoperation_type_name__perevod_mezhdu_svoimi_schetami: float | None
    bki_active_auto_cnt: str | None
    turn_other_cr_avg_act_v2: float | None
    cntVoiceOutMob6m: float | None
    avg_by_category__amount__sum__cashflowcategory_name__puteshestvija: float | None
    loanacc_rur_amt_cm_avg: float | None
    transaction_category_supermarket_sum_cnt_m2: float | None
    transaction_category_supermarket_sum_amt_d15: float | None
    avg_fdep_cr_turn: float | None
    transaction_category_restaurants_percent_cnt_2m: float | None
    bki_total_max_limit: str | None
    avg_by_category__amount__sum__cashflowcategory_name__reklama_v_internete: float | None
    transaction_category_restaurants_percent_amt_2m: float | None
    turn_fdep_db_avg_act_v2: float | None
    dp_ils_accpayment_avg_6m: float | None
    turn_other_cr_sum_v2: float | None
    client_active_flag: float | None
    avg_by_category__amount__sum__cashflowcategory_name__produkty: float | None
    curr_rur_amt_cm_avg_inc_v2: float | None
    nonresident_flag: float | None
    avg_by_category__amount__sum__cashflowcategory_name__kosmetika: float | None
    vert_has_app_ru_vtb_invest: float | None
    dp_ils_avg_salary_3y: float | None
    hdb_bki_total_auto_max_limit: str | None
    days_after_last_request: float | None
    cntRegionTripsWavg1m: float | None
    vert_has_app_ru_cian_main: float | None
    loanacc_rur_amt_curr_v2: float | None
    avg_3m_no_cat: float | None
    vert_ghost_close_dpay3_last_days: float | None
    vert_has_app_ru_raiffeisennews: float | None
    dp_ils_days_ip_share_5y: float | None
    avg_by_category__amount__sum__cashflowcategory_name__platezhi_cherez_internet: float | None
    hdb_bki_total_micro_max_overdue: str | None
    bki_total_active_products: str | None
    by_category__amount__sum__eoperation_type_name__perevod_s_karty_na_kartu: float | None
    calledCtnOutGroup: float | None
    vert_pil_loan_application_success_3m: float | None
    vert_pil_fee_discount_change_3m: float | None
    businessTelSubs: float | None
    profit_income_out_rur_amt_l2m: float | None
    avg_3m_healthcare_services: float | None
    dp_ils_paymentssum_month_avg: float | None
    ovrd_sum: float | None
    hdb_bki_total_active_products: str | None
    hdb_bki_total_micro_cnt: str | None
    hdb_bki_active_pil_cnt: str | None
    loan_cur_amt: float | None
    mob_total_sessions: float | None
    period_last_act_ad: str | None
    dp_ils_days_multiple_job_share_2y: float | None
    hdb_bki_total_cc_max_overdue: str | None
    lifetimeComp: float | None
    hdb_bki_total_pil_last_days: str | None
    amount_by_category_90d__summarur_amt__sum__cashflowcategory_name__elektronnye_dengi: float | None
    turn_save_cr_max_v2: float | None
    hdb_bki_active_pil_max_limit: str | None
    dp_ils_accpayment_avg_3m: float | None
    avg_6m_restaurants: float | None
    hdb_bki_total_pil_cnt: str | None
    transaction_category_fastfood_percent_cnt_2m: float | None
    hdb_bki_total_pil_max_del90: str | None
    accountsalary_out_flag: float | None
    cntBlockWavg6m: float | None
    express_rur_amt_cm_avg: float | None
    loanacc_rur_amt_cm_avg_inc_v2: float | None
    hdb_bki_last_product_days: str | None
    dp_ils_days_multiple_job_cnt_5y: float | None
    dp_ils_accpayment_month_avg: float | None
    cred_dda_rur_amt_3m_avg: float | None
    avg_3m_all: float | None
    hdb_other_active_max_psk: float | None
    hdb_bki_other_active_ip_outstanding: str | None
    total_sum: float | None
    dp_ils_uniq_companies_1y: float | None
    avg_6m_travel: float | None
    avg_6m_government_services: float | None
    hdb_bki_active_cc_max_overdue: str | None
    total_rur_amt_cm_avg_period_days_ago_v2: float | None
    label_Above_1M_share_r1: float | None
    transaction_category_supermarket_sum_cnt_d15: float | None
    max_balance_rur_amt_1m_af: float | None
    first_salary_income: float | None

    def to_dataframe(self):
        return pd.DataFrame([self.model_dump()])
    
class OutputData(BaseModel):
    prediction: float